FROM eclipse-temurin:21

EXPOSE 8083

ADD target/NotificationMicroService-0.0.1-SNAPSHOT.jar NotificationMicroService-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "NotificationMicroService-0.0.1-SNAPSHOT.jar"]